lint_codebase:
  stage: check
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  script:
    - poetry install --with dev
    - mkdir -p $CHECK_REPORT_PATH'/mypy'
    - echo "Checking codebase ..."
    - poetry run ruff check -show-fixes --config=$CHECK_CONFIG_PATH'ruff.toml' | tee $CHECK_REPORT_PATH'ruff_check.ansi' || true
    - poetry run mypy src/ --config-file $CHECK_CONFIG_PATH'mypy.ini' | tee $CHECK_REPORT_PATH'mypy/mypy_check.ansi' || true
    - echo "Successfully checked codebase."
  artifacts:
    paths:
      - "$CHECK_REPORT_PATH"
    when: always
    expire_in: 30 days
